version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - bodyclose
    - copyloopvar
    - gocritic
    - gosec
    - misspell
    - noctx
    - revive
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      disabled-checks:
        - unnecessaryDefer
      enabled-tags:
        - diagnostic
        - style
        - performance
    gosec:
      excludes:
        - G104
    govet:
      enable:
        - shadow
    revive:
      confidence: 0.8
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - errcheck
        path: cmd/api/main\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
