coverage:
  status:
    project:
      default:
        target: 10%          # Minimum coverage target
        threshold: 5%        # Allow 5% drop
    patch:
      default:
        target: 80%          # New code should have higher coverage

comment:
  require_changes: true      # Only comment if coverage changed
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - "cmd/**"                 # Ignore main.go
  - "**/*_test.go"           # Ignore test files
  - "internal/config/**"     # Ignore config (simple getters)